package com.studentmanagement.model;

import java.sql.Timestamp;

/**
 * Student.java
 * =============
 * PURPOSE: Represents a single student record from the database.
 *
 * WHY THIS CLASS EXISTS:
 *   This is the "Model" — a plain Java object (POJO) that mirrors one row
 *   of the `students` table in MySQL. When we fetch data from the database
 *   using JDBC, we store it in Student objects. When we want to save data,
 *   we create a Student object and pass it to the DAO layer.
 *
 * FIELDS MAP TO DATABASE COLUMNS:
 *   Java Field    →  MySQL Column
 *   ---------        ------------
 *   id            →  id
 *   name          →  name
 *   email         →  email
 *   phone         →  phone
 *   age           →  age
 *   gender        →  gender
 *   course        →  course
 *   department    →  department
 *   semester      →  semester
 *   address       →  address
 *   createdAt     →  created_at
 */
public class Student {

    // Private fields — encapsulation (OOP principle)
    private int id;
    private String name;
    private String email;
    private String phone;
    private int age;
    private String gender;
    private String course;
    private String department;
    private int semester;
    private String address;
    private Timestamp createdAt;

    /**
     * Default constructor — needed when we create an empty Student
     * and then set fields one by one using setters.
     */
    public Student() {
    }

    /**
     * Full constructor — used when we have all fields available
     * (e.g., when reading from the database with ResultSet).
     */
    public Student(int id, String name, String email, String phone, int age,
                   String gender, String course, String department,
                   int semester, String address, Timestamp createdAt) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.age = age;
        this.gender = gender;
        this.course = course;
        this.department = department;
        this.semester = semester;
        this.address = address;
        this.createdAt = createdAt;
    }

    /**
     * Constructor WITHOUT id and createdAt — used when adding a new student.
     * The id is auto-generated by MySQL (AUTO_INCREMENT).
     * The created_at is set by MySQL (DEFAULT CURRENT_TIMESTAMP).
     */
    public Student(String name, String email, String phone, int age,
                   String gender, String course, String department,
                   int semester, String address) {
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.age = age;
        this.gender = gender;
        this.course = course;
        this.department = department;
        this.semester = semester;
        this.address = address;
    }

    // ===== GETTERS AND SETTERS =====
    // These follow Java Bean conventions: private fields + public get/set methods

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getCourse() {
        return course;
    }

    public void setCourse(String course) {
        this.course = course;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public int getSemester() {
        return semester;
    }

    public void setSemester(int semester) {
        this.semester = semester;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * toString() — returns a human-readable representation of the student.
     * Useful for debugging and console display.
     */
    @Override
    public String toString() {
        return String.format(
            "Student{id=%d, name='%s', email='%s', phone='%s', age=%d, " +
            "gender='%s', course='%s', department='%s', semester=%d, address='%s'}",
            id, name, email, phone, age, gender, course, department, semester, address
        );
    }
}
